// Import necessary modules in your Angular service
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  private apiUrl = 'https://test.beneficiar.com.co/TestConsultaCifin/ConsultaCifinIsapi.dll/api/rest/TServerMethodCifin/ConsultarBD';

  constructor(private http: HttpClient) {}

  consultarBD(): Observable<any> {
    // Basic auth username and password
    const username = 'ServerAdmin';
    const password = 'B3N3F1C14R_R3ST';
    const credentials = btoa(`${username}:${password}`); // Encode credentials to base64

    // Set headers
    const headers = new HttpHeaders({
      'Authorization': `Basic ${credentials}`,
      'Content-Type': 'application/json'
    });

    // Request body
    const body = {
      Tipo: "1",
      Numero: "3167398",
      Motivo: "24",
      Codigo: "154",
      FECHACONSULTA: "07/12/2024",
      IdCentralCred: "1"
    };

    // Send POST request
    return this.http.post(this.apiUrl, body, { headers });
  }
  getBeneficiarInfo(cc:string){
    if(cc==='3167398')
    return this.beneficiar["3167398"].result;
    else return this.beneficiar["80170625"].result;
  }
  getCifinProducts(documento:string){
    console.log(documento);
    if(documento==='3167398')
    return this.cifin["3167398"].result.JAObligaciones;
    else return this.cifin["80170625"].result.JAObligaciones;
  }
  hola = { "a": { "a": "asd", "b": "asjdhb" }, "b": { "a": "asd", "b": "asjdhb" } };
cifin={
  "3167398":{
    "result": {
        "IDCICREDTERCERO": "6426",
        "IDCENTRALCRED": "1",
        "FECHA": "10/21/2024",
        "HORA": "10:27:26",
        "IDENTIFICADORLINEA": "14980213",
        "TIPOIDENTIFICACION": "C.C.",
        "NUMEROIDENTIFICACION": "3167398",
        "NOMBRETITULAR": "BOHORQUEZ  ROJAS DIEGO ALEXANDER",
        "LUGAREXPEDICION": "",
        "FECHAEXPEDICION": "08/06/1999",
        "ESTADO": "VIGENTE",
        "NUMEROINFORME": "06187551280605528104",
        "RANGOEDAD": "41-45",
        "CODIGOCIIU": "null",
        "CODIGODEPARTAMENTO": "25",
        "CODIGOMUNICIPIO": "718",
        "RESPUESTACONSULTA": "2",
        "ENTIDAD": "COOP BENEFICIAR- COOP. DE AHORRO Y",
        "CODIGOTIPOIDENTIFICACION": "1",
        "NOMBRECIU": "null",
        "ESTADOTITULAR": "null",
        "NOMBRE1": "DIEGO",
        "NOMBRE2": "ALEXANDER",
        "APELLIDO1": "BOHORQUEZ",
        "APELLIDO2": "ROJAS",
        "CALIFICACION": "A",
        "CodError": "0",
        "JAConsolidado": [
            {
                "IDCENTRIESGOCONSOLIDADO": "32422",
                "PAQUETEINFORMACION": "'Sector Solidario'",
                "NUMEROOBLIGACIONES": "3",
                "TOTALSALDO": "85501",
                "PARTICIPACIONDEUDA": "100",
                "NUMEROOBLIGACIONESDIA": "3",
                "SALDOOBLIGACIONESDIA": "85501",
                "CUOTAOBLIGACIONESDIA": "2559",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "32423",
                "PAQUETEINFORMACION": "'Sector Real'",
                "NUMEROOBLIGACIONES": "3",
                "TOTALSALDO": "0",
                "PARTICIPACIONDEUDA": "0",
                "NUMEROOBLIGACIONESDIA": "3",
                "SALDOOBLIGACIONESDIA": "0",
                "CUOTAOBLIGACIONESDIA": "105",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "32424",
                "PAQUETEINFORMACION": "'Subtotal Principal'",
                "NUMEROOBLIGACIONES": "6",
                "TOTALSALDO": "85501",
                "PARTICIPACIONDEUDA": "100",
                "NUMEROOBLIGACIONESDIA": "6",
                "SALDOOBLIGACIONESDIA": "85501",
                "CUOTAOBLIGACIONESDIA": "2664",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "32425",
                "PAQUETEINFORMACION": "'Total'",
                "NUMEROOBLIGACIONES": "6",
                "TOTALSALDO": "85501",
                "PARTICIPACIONDEUDA": "100",
                "NUMEROOBLIGACIONESDIA": "6",
                "SALDOOBLIGACIONESDIA": "85501",
                "CUOTAOBLIGACIONESDIA": "2664",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "2"
            }
        ],
        "JAObligaciones": [
            {
                "IDCENTRALINFCOMERCIAL": "237788",
                "IDCENTRALINFCREDTERCERO": "6426",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0021",
                "IDENTIFICADORLINEA": "215224075",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "null",
                "TIPOENTIDAD": "COOP",
                "NOMBREENTIDAD": "BENEFICIAR- COOP. DE AHORRO Y",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "BOGOTA",
                "NUMEROOBLIGACION": "810249",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "CONS",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "09/02/2020",
                "FECHATERMINACION": "08/25/2030",
                "CALIFICACION": "",
                "VALORINICIAL": "100000",
                "SALDOOBLIGACION": "71199",
                "VALORMORA": "0",
                "VALORCUOTA": "1431",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "49",
                "TIPOGARANTIA": "OTRA",
                "CUBRIMIENTOGARANTIA": "87.1",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "N |N |N |N |X |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "83",
                "PROBABILIDADNOPAGO": "0",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "120",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "237789",
                "IDCENTRALINFCREDTERCERO": "6426",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0021",
                "IDENTIFICADORLINEA": "279695976",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "null",
                "TIPOENTIDAD": "COOP",
                "NOMBREENTIDAD": "BENEFICIAR- COOP. DE AHORRO Y",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "BOGOTA",
                "NUMEROOBLIGACION": "864878",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "CONS",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "05/08/2024",
                "FECHATERMINACION": "04/25/2025",
                "CALIFICACION": "",
                "VALORINICIAL": "8000",
                "SALDOOBLIGACION": "4770",
                "VALORMORA": "0",
                "VALORCUOTA": "711",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "5",
                "TIPOGARANTIA": "OTRA",
                "CUBRIMIENTOGARANTIA": "87.1",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "6",
                "PROBABILIDADNOPAGO": "0",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "12",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "237790",
                "IDCENTRALINFCREDTERCERO": "6426",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0021",
                "IDENTIFICADORLINEA": "145554513",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "null",
                "TIPOENTIDAD": "COOP",
                "NOMBREENTIDAD": "BENEFICIAR- COOP. DE AHORRO Y",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "BOGOTA",
                "NUMEROOBLIGACION": "T16406",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "LBLI",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "07/19/2016",
                "FECHATERMINACION": "07/19/2018",
                "CALIFICACION": "",
                "VALORINICIAL": "10000",
                "SALDOOBLIGACION": "9532",
                "VALORMORA": "0",
                "VALORCUOTA": "417",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "1",
                "TIPOGARANTIA": "OTRA",
                "CUBRIMIENTOGARANTIA": "87.1",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "11",
                "PROBABILIDADNOPAGO": "0",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "24",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            }
        ]
    }
}

  ,"80170625":{
    "result": {
        "IDCICREDTERCERO": "6821",
        "IDCENTRALCRED": "1",
        "FECHA": "11/01/2024",
        "HORA": "07:08:19",
        "IDENTIFICADORLINEA": "35256717",
        "TIPOIDENTIFICACION": "C.C.",
        "NUMEROIDENTIFICACION": "80170625",
        "NOMBRETITULAR": "BUITRAGO  CELEITA ANDRES GEOVANNY",
        "LUGAREXPEDICION": "",
        "FECHAEXPEDICION": "03/01/2000",
        "ESTADO": "VIGENTE",
        "NUMEROINFORME": "06195973350606370309",
        "RANGOEDAD": "41-45",
        "CODIGOCIIU": "4923",
        "CODIGODEPARTAMENTO": "11",
        "CODIGOMUNICIPIO": "1",
        "RESPUESTACONSULTA": "2",
        "ENTIDAD": "COOP BENEFICIAR- COOP. DE AHORRO Y",
        "CODIGOTIPOIDENTIFICACION": "1",
        "NOMBRECIU": "TRANSPORTE DE CARGA POR CARRETERA",
        "ESTADOTITULAR": "null",
        "NOMBRE1": "ANDRES",
        "NOMBRE2": "GEOVANNY",
        "APELLIDO1": "BUITRAGO",
        "APELLIDO2": "CELEITA",
        "CALIFICACION": "A",
        "CodError": "0",
        "JAConsolidado": [
            {
                "IDCENTRIESGOCONSOLIDADO": "34397",
                "PAQUETEINFORMACION": "'Tarjetas De Credito'",
                "NUMEROOBLIGACIONES": "1",
                "TOTALSALDO": "20106",
                "PARTICIPACIONDEUDA": "19",
                "NUMEROOBLIGACIONESDIA": "1",
                "SALDOOBLIGACIONESDIA": "20106",
                "CUOTAOBLIGACIONESDIA": "0",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "34398",
                "PAQUETEINFORMACION": "'Sector Financiero'",
                "NUMEROOBLIGACIONES": "19",
                "TOTALSALDO": "58084",
                "PARTICIPACIONDEUDA": "55",
                "NUMEROOBLIGACIONESDIA": "19",
                "SALDOOBLIGACIONESDIA": "58084",
                "CUOTAOBLIGACIONESDIA": "880",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "34399",
                "PAQUETEINFORMACION": "'Sector Solidario'",
                "NUMEROOBLIGACIONES": "1",
                "TOTALSALDO": "28152",
                "PARTICIPACIONDEUDA": "26",
                "NUMEROOBLIGACIONESDIA": "1",
                "SALDOOBLIGACIONESDIA": "28152",
                "CUOTAOBLIGACIONESDIA": "1260",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "34400",
                "PAQUETEINFORMACION": "'Subtotal Principal'",
                "NUMEROOBLIGACIONES": "21",
                "TOTALSALDO": "106342",
                "PARTICIPACIONDEUDA": "100",
                "NUMEROOBLIGACIONESDIA": "21",
                "SALDOOBLIGACIONESDIA": "106342",
                "CUOTAOBLIGACIONESDIA": "2140",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "1"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "34401",
                "PAQUETEINFORMACION": "'Sector Solidario'",
                "NUMEROOBLIGACIONES": "1",
                "TOTALSALDO": "42763",
                "PARTICIPACIONDEUDA": "",
                "NUMEROOBLIGACIONESDIA": "1",
                "SALDOOBLIGACIONESDIA": "42763",
                "CUOTAOBLIGACIONESDIA": "1908",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "2"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "34402",
                "PAQUETEINFORMACION": "'Subtotal Codeudores'",
                "NUMEROOBLIGACIONES": "1",
                "TOTALSALDO": "42763",
                "PARTICIPACIONDEUDA": "",
                "NUMEROOBLIGACIONESDIA": "1",
                "SALDOOBLIGACIONESDIA": "42763",
                "CUOTAOBLIGACIONESDIA": "1908",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "2"
            },
            {
                "IDCENTRIESGOCONSOLIDADO": "34403",
                "PAQUETEINFORMACION": "'Total'",
                "NUMEROOBLIGACIONES": "22",
                "TOTALSALDO": "149105",
                "PARTICIPACIONDEUDA": "100",
                "NUMEROOBLIGACIONESDIA": "22",
                "SALDOOBLIGACIONESDIA": "149105",
                "CUOTAOBLIGACIONESDIA": "4048",
                "CANTIDADOBLIGACIONESMORA": "0",
                "SALDOOBLIGACIONESMORA": "0",
                "CUOTAOBLIGACIONESMORA": "0",
                "VALORMORA": "0",
                "TIPORESUMEN": "2"
            }
        ],
        "JAObligaciones": [
            {
                "IDCENTRALINFCOMERCIAL": "252431",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "267666917",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "094793",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "07/22/2023",
                "FECHATERMINACION": "03/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1000",
                "SALDOOBLIGACION": "834",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "14",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252432",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "267648763",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "094063",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "07/01/2023",
                "FECHATERMINACION": "03/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "2500",
                "SALDOOBLIGACION": "1731",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "14",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252433",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "273981413",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "099790",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "12/06/2023",
                "FECHATERMINACION": "08/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "4000",
                "SALDOOBLIGACION": "3603",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "9",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "2",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252434",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "271256852",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "097685",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "10/11/2023",
                "FECHATERMINACION": "06/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1000",
                "SALDOOBLIGACION": "873",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "11",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252435",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "265450887",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "092254",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "05/14/2023",
                "FECHATERMINACION": "01/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "2000",
                "SALDOOBLIGACION": "1642",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "16",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252436",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "279056818",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "104131",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "04/19/2024",
                "FECHATERMINACION": "12/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "4600",
                "SALDOOBLIGACION": "4296",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "5",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "3",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252437",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "279111974",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "103717",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "04/07/2024",
                "FECHATERMINACION": "12/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "2000",
                "SALDOOBLIGACION": "1890",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "5",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252438",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "269280140",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "096116",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "08/30/2023",
                "FECHATERMINACION": "05/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "800",
                "SALDOOBLIGACION": "681",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "12",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "0",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252439",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "271465830",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "098260",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "10/26/2023",
                "FECHATERMINACION": "07/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "500",
                "SALDOOBLIGACION": "445",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "10",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "0",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252440",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "273115747",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "099020",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "11/16/2023",
                "FECHATERMINACION": "07/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1500",
                "SALDOOBLIGACION": "1318",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "10",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252441",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "276834907",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "101997",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "02/15/2024",
                "FECHATERMINACION": "10/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1500",
                "SALDOOBLIGACION": "1376",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "7",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252442",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "269127770",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "095436",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "08/09/2023",
                "FECHATERMINACION": "04/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1000",
                "SALDOOBLIGACION": "858",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "13",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252443",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "269240234",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "095890",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "08/23/2023",
                "FECHATERMINACION": "04/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1000",
                "SALDOOBLIGACION": "843",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "13",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252444",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "270171935",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "096964",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "09/21/2023",
                "FECHATERMINACION": "05/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1300",
                "SALDOOBLIGACION": "1116",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "12",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252445",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "271992091",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "098072",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "10/21/2023",
                "FECHATERMINACION": "06/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "1500",
                "SALDOOBLIGACION": "1290",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "11",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "1",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "68",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252446",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "279098853",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "BANCOLOMBIA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "CENTRO  INTERNAC",
                "NUMEROOBLIGACION": "103882",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ROTA",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "04/12/2024",
                "FECHATERMINACION": "12/15/2029",
                "CALIFICACION": "",
                "VALORINICIAL": "11000",
                "SALDOOBLIGACION": "10345",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "5",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "7",
                "PROBABILIDADNOPAGO": "75",
                "FECHACORTE": "09/28/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "69",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252448",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0006",
                "IDENTIFICADORLINEA": "231991405",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "DE BOGOTA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "ISS - CANN",
                "NUMEROOBLIGACION": "520841",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "ORDI",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "09/01/2021",
                "FECHATERMINACION": "09/05/2027",
                "CALIFICACION": "",
                "VALORINICIAL": "53457",
                "SALDOOBLIGACION": "24943",
                "VALORMORA": "0",
                "VALORCUOTA": "880",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "37",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "17",
                "PROBABILIDADNOPAGO": "0",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "72",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252449",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0002",
                "IDENTIFICADORLINEA": "85885167",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "VIGE",
                "TIPOENTIDAD": "BCO",
                "NOMBREENTIDAD": "DE BOGOTA",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "ISS - CANN",
                "NUMEROOBLIGACION": "2453",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "TCR",
                "PERIODICIDAD": "",
                "FECHAAPERTURA": "08/19/2021",
                "FECHATERMINACION": "",
                "CALIFICACION": "",
                "VALORINICIAL": "18450",
                "SALDOOBLIGACION": "20106",
                "VALORMORA": "0",
                "VALORCUOTA": "0",
                "TIPOMONEDA": "",
                "CUOTASCANCELADAS": "",
                "TIPOGARANTIA": "",
                "CUBRIMIENTOGARANTIA": "",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "13",
                "PROBABILIDADNOPAGO": "",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "MAS",
                "CLASETARJETA": "MCG",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252451",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0021",
                "IDENTIFICADORLINEA": "258364893",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "null",
                "TIPOENTIDAD": "COOP",
                "NOMBREENTIDAD": "BENEFICIAR- COOP. DE AHORRO Y",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "BOGOTA",
                "NUMEROOBLIGACION": "847728",
                "CALIDAD": "PRIN",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "CONS",
                "LINEACREDITO": "CONS",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "02/21/2023",
                "FECHATERMINACION": "02/21/2027",
                "CALIFICACION": "",
                "VALORINICIAL": "40000",
                "SALDOOBLIGACION": "28152",
                "VALORMORA": "0",
                "VALORCUOTA": "1260",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "19",
                "TIPOGARANTIA": "PERS",
                "CUBRIMIENTOGARANTIA": "0",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "|  |  |  |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "19",
                "PROBABILIDADNOPAGO": "0",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "48",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            },
            {
                "IDCENTRALINFCOMERCIAL": "252452",
                "IDCENTRALINFCREDTERCERO": "6821",
                "TIPOCOMERCIALOBLIGACION": "3",
                "PAQUETEINFORMACION": "0021",
                "IDENTIFICADORLINEA": "176658444",
                "TIPOCONTRATO": "CRE",
                "ESTADOCONTRATO": "null",
                "TIPOENTIDAD": "COOP",
                "NOMBREENTIDAD": "BENEFICIAR- COOP. DE AHORRO Y",
                "CIUDAD": "BOGOTA",
                "SUCURSAL": "BOGOTA",
                "NUMEROOBLIGACION": "544201",
                "CALIDAD": "DSOL",
                "ESTADOOBLIGACION": "VIGE",
                "MODALIDADCREDITO": "VIVI",
                "LINEACREDITO": "VIVI",
                "PERIODICIDAD": "MEN",
                "FECHAAPERTURA": "07/11/2018",
                "FECHATERMINACION": "02/17/2027",
                "CALIFICACION": "",
                "VALORINICIAL": "120000",
                "SALDOOBLIGACION": "42763",
                "VALORMORA": "0",
                "VALORCUOTA": "1908",
                "TIPOMONEDA": "ML",
                "CUOTASCANCELADAS": "74",
                "TIPOGARANTIA": "OTRA",
                "CUBRIMIENTOGARANTIA": "236.5",
                "MORAMAXIMA": "",
                "COMPORTAMIENTOS": "N |N |N |N |X |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |N |",
                "PARTICIPACIONDEUDA": "29",
                "PROBABILIDADNOPAGO": "0",
                "FECHACORTE": "09/30/2024",
                "MODOEXTINCION": "null",
                "FECHAPAGO": "",
                "FECHAPERMANENCIA": "",
                "NUMEROREESTRUCTURACIONES": "",
                "NATURALEZAREESTRUCTURACION": "",
                "MARCATARJETA": "",
                "CLASETARJETA": "",
                "TIPOFIDECOMISO": "",
                "TIPOENTIDADORIGINADORACARTERA": "",
                "ENTIDADORIGINADORACARTERA": "",
                "NUMEROFIDEICOMISO": "",
                "CHEQUESDEVUELTOS": "",
                "PLAZO": "",
                "DIASCARTERA": "",
                "TIPOPAGO": "",
                "ESTADOTITULAR": "NORM",
                "NUMEROCUOTASPACTADAS": "100",
                "NUMEROCUOTASMORA": "0",
                "VALORCARGOFIJO": "",
                "CLAUSURAPERMANENCIA": "",
                "REESTRUCTURADO": "",
                "VIGENCIA": "",
                "NUMEROMESESCONTRATO": "",
                "NUMEROMESESCLAUSULA": ""
            }
        ]
    }
}
}
beneficiar={
    "3167398":
    {
        "result": [
            {
                "Cedula": "3167398",
                "Nombre": "PRUEBAS  BENEFICIAR AMBIENTE DE",
                "Entidad": "BENEFICIAR ENTIDAD COOPERATIVA",
                "TipoContrato": "TERMINO INDEFINIDO",
                "Afiliado": "09/16/2011",
                "Retirado": "",
                "Estado": "2",
                "DesEstado": "ACTIVO",
                "Salario": "9688000",
                "PlaExequial": "S",
                "CodAsociado": "40160",
                "CodError": 0,
                "Registros": [
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "2",
                        "DESCRIPCION": "Aporte y ahorros permanentes",
                        "VALORCONSOLIDADO": "55399449"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "4",
                        "DESCRIPCION": "Productos de ahorro",
                        "VALORCONSOLIDADO": "7089704"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "1",
                        "DESCRIPCION": "Saldos credito (Capital)",
                        "VALORCONSOLIDADO": "75969038"
                    },
                    {
                        "IDSUBPRODUCTO": "24",
                        "IDPRODUCTO": "5",
                        "DESCRIPCION": "Saldo credito rotativo",
                        "VALORCONSOLIDADO": "9531521"
                    },
                    {
                        "IDSUBPRODUCTO": "23",
                        "IDPRODUCTO": "5",
                        "DESCRIPCION": "Saldo tarjeta Debito",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "8",
                        "DESCRIPCION": "Servicios complementarios",
                        "VALORCONSOLIDADO": "176702"
                    },
                    {
                        "IDSUBPRODUCTO": "1",
                        "IDPRODUCTO": "2",
                        "DESCRIPCION": "Interes al ahorro permanente 2023",
                        "VALORCONSOLIDADO": "3441030"
                    }
                ]
            }
        ]
    },
    "80170625":
    {
        "result": [
            {
                "Cedula": "80170625",
                "Nombre": "ANDRES GEOVANNY BUITRAGO CELEITA",
                "Entidad": "ASOCIADO INDEPENDIENTE",
                "TipoContrato": "PRESTACION SERVICIOS",
                "Afiliado": "01/19/2015",
                "Retirado": "",
                "Estado": "2",
                "DesEstado": "ACTIVO",
                "Salario": "2500000",
                "PlaExequial": "S",
                "CodAsociado": "33792",
                "CodError": 0,
                "Registros": [
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "2",
                        "DESCRIPCION": "Aporte y ahorros permanentes",
                        "VALORCONSOLIDADO": "19285210"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "4",
                        "DESCRIPCION": "Productos de ahorro",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "1",
                        "DESCRIPCION": "Saldos credito (Capital)",
                        "VALORCONSOLIDADO": "28151937"
                    },
                    {
                        "IDSUBPRODUCTO": "24",
                        "IDPRODUCTO": "5",
                        "DESCRIPCION": "Saldo credito rotativo",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "23",
                        "IDPRODUCTO": "5",
                        "DESCRIPCION": "Saldo tarjeta Debito",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "8",
                        "DESCRIPCION": "Servicios complementarios",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "1",
                        "IDPRODUCTO": "2",
                        "DESCRIPCION": "Interes al ahorro permanente 2023",
                        "VALORCONSOLIDADO": "1008275"
                    }
                ]
            }
        ]
    },
    "52551760":
    {
        "result": [
            {
                "Cedula": "52551760",
                "Nombre": "OLGA PATRICIA GONZALEZ CELEITA",
                "Entidad": "BANCO DE BOGOTA",
                "TipoContrato": "TERMINO INDEFINIDO",
                "Afiliado": "08/13/2007",
                "Retirado": "03/15/2007",
                "Estado": "2",
                "DesEstado": "ACTIVO",
                "Salario": "3200000",
                "PlaExequial": "S",
                "CodAsociado": "614000",
                "CodError": 0,
                "Registros": [
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "2",
                        "DESCRIPCION": "Aporte y ahorros permanentes",
                        "VALORCONSOLIDADO": "27861227"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "4",
                        "DESCRIPCION": "Productos de ahorro",
                        "VALORCONSOLIDADO": "149495"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "1",
                        "DESCRIPCION": "Saldos credito (Capital)",
                        "VALORCONSOLIDADO": "42763089"
                    },
                    {
                        "IDSUBPRODUCTO": "24",
                        "IDPRODUCTO": "5",
                        "DESCRIPCION": "Saldo credito rotativo",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "23",
                        "IDPRODUCTO": "5",
                        "DESCRIPCION": "Saldo tarjeta Debito",
                        "VALORCONSOLIDADO": "0"
                    },
                    {
                        "IDSUBPRODUCTO": "0",
                        "IDPRODUCTO": "8",
                        "DESCRIPCION": "Servicios complementarios",
                        "VALORCONSOLIDADO": "37536"
                    },
                    {
                        "IDSUBPRODUCTO": "1",
                        "IDPRODUCTO": "2",
                        "DESCRIPCION": "Interes al ahorro permanente 2023",
                        "VALORCONSOLIDADO": "1793876"
                    }
                ]
            }
        ]
    },

}
}
